# Generated by Django 3.2.4 on 2021-06-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojosninjas', '0004_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='dojo antiguo'),
        ),
    ]
