# Generated by Django 3.2.4 on 2021-06-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojosninjas', '0005_alter_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
